slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    odom_frame: odom
    map_frame: map
    base_frame: zero_base_link
    scan_topic: /scan
    mode: mapping
    resolution: 0.05
    transform_publish_period: 0.02
    map_update_interval: 5.0
    use_sim_time: true
